"""empty message

Revision ID: 401560ec4dbb
Revises: 2c7587b7f976
Create Date: 2026-02-02 18:06:44.632682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401560ec4dbb'
down_revision = '2c7587b7f976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_constraint('character_planet_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.create_unique_constraint('character_planet_id_key', ['planet_id'])

    # ### end Alembic commands ###
